### ISSUE TITLE
Util from echarts

### ISSUE THREAD

**Issue by parvezshah** [xieziyu/ngx-echarts#244] opened 2020-06-24 07:45 UTC
i am trying to use util
from the example https://echarts.apache.org/examples/en/editor.html?c=line-draggable
I cant use util as it's not exported.
Is there any other way to use util package

**Comment by Santiago8888** [comment] 2020-07-01 06:33
Duplicate of #199.
Appart from the solution presented there you can just cast echarts with type any.

**Comment by xieziyu** [comment] 2020-08-11 11:41
Please open issue in `@types/echarts`

**Closed by xieziyu** 2020-08-11 11:41 UTC
